#    미국 주와 주별 인구 데이타 예제 
     - 2010년도 인구 밀도 기준으로 미국 주와 지역 순위를 출력
 
1. 데이타를 로딩 후 데이타 정보 확인


2. 데이타 연결
        1- 인구 데이타와 주이름 약어 데이타를 연결
            ( 각 주의 전체 이름과 인구를 볼 수 있도록 )
            
        2- 각 주의 인구 데이타와 면적 데이타를 연결
            ( 각 주의 면적당 인구를 계산하여 인구 밀도를 구하기 )
            
3. 데이타 정제(데이타 전처리)
     * 누락값 처리
        1. 삭제한다
        2. 대체한다
    
    실제로 2000년 이전의 PR(푸에르토리토)의 인구 데이타가 없는 것이다.
    여기서는 2010년 데이타를 구할 것이기에 삭제해도 되지만 대체하는 방식을 연습한다
    또한 전체 미국을 뜻하는 USA에 state와 abbreviation이 없다.
 
 
4. 2010년 인구밀도 계산하고 표현
        인구밀도 = 인구 / 면적
        

 
    [도서] 파이썬 데이타 사이언스 핸드북 - 위키북스/오렐리

---
## 1. 데이타를 로딩 후 데이타 정보 확인

In [31]:
# 1. 데이타를 로딩 후 데이타 정보 확인
import pandas as pd

pop = pd.read_csv('./data/state-population.csv')    # 주별 인구
areas = pd.read_csv('./data/state-areas.csv')       # 주의 면적
abbrevs = pd.read_csv('./data/state-abbrevs.csv')   # 주이름 약자

# 데이타 살펴보기
print(pop)

print()
print(areas)

# 행수 확인
#pop.shape

#abbrevs에 Puerto Rico PR 추가
abbrevs.loc[51]=['Puerto Rico','PR']
print(abbrevs)

     state/region     ages  year   population
0              AL  under18  2012    1117489.0
1              AL    total  2012    4817528.0
2              AL  under18  2010    1130966.0
3              AL    total  2010    4785570.0
4              AL  under18  2011    1125763.0
5              AL    total  2011    4801627.0
6              AL    total  2009    4757938.0
7              AL  under18  2009    1134192.0
8              AL  under18  2013    1111481.0
9              AL    total  2013    4833722.0
10             AL    total  2007    4672840.0
11             AL  under18  2007    1132296.0
12             AL    total  2008    4718206.0
13             AL  under18  2008    1134927.0
14             AL    total  2005    4569805.0
15             AL  under18  2005    1117229.0
16             AL    total  2006    4628981.0
17             AL  under18  2006    1126798.0
18             AL    total  2004    4530729.0
19             AL  under18  2004    1113662.0
20             AL    total  2003    4503491.0
21             AL  under18  2003    1113083.0
22             AL    total  2001    4467634.0
23             AL  under18  2001    1120409.0
24             AL    total  2002    4480089.0
25             AL  under18  2002    1116590.0
26             AL  under18  1999    1121287.0
27             AL    total  1999    4430141.0
28             AL    total  2000    4452173.0
29             AL  under18  2000    1122273.0
...           ...      ...   ...          ...
2514          USA  under18  1999   71946051.0
2515          USA    total  2000  282162411.0
2516          USA  under18  2000   72376189.0
2517          USA    total  1999  279040181.0
2518          USA    total  2001  284968955.0
2519          USA  under18  2001   72671175.0
2520          USA    total  2002  287625193.0
2521          USA  under18  2002   72936457.0
2522          USA    total  2003  290107933.0
2523          USA  under18  2003   73100758.0
2524          USA    total  2004  292805298.0
2525          USA  under18  2004   73297735.0
2526          USA    total  2005  295516599.0
2527          USA  under18  2005   73523669.0
2528          USA    total  2006  298379912.0
2529          USA  under18  2006   73757714.0
2530          USA    total  2007  301231207.0
2531          USA  under18  2007   74019405.0
2532          USA    total  2008  304093966.0
2533          USA  under18  2008   74104602.0
2534          USA  under18  2013   73585872.0
2535          USA    total  2013  316128839.0
2536          USA    total  2009  306771529.0
2537          USA  under18  2009   74134167.0
2538          USA  under18  2010   74119556.0
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

[2544 rows x 4 columns]

                   state  area (sq. mi)
0                Alabama          52423
1                 Alaska         656425
2                Arizona         114006
3               Arkansas          53182
4             California         163707
5               Colorado         104100
6            Connecticut           5544
7               Delaware           1954
8                Florida          65758
9                Georgia          59441
10                Hawaii          10932
11                 Idaho          83574
12              Illinois          57918
13               Indiana          36420
14                  Iowa          56276
15                Kansas          82282
16              Kentucky          40411
17             Louisiana          51843
18                 Maine          35387
19              Maryland          12407
20         Massachusetts          10555
21              Michigan          96810
22             Minnesota          86943
23           Mississippi          48434
24              Missouri          69709
25               Montana         147046
26              Nebraska          77358
27                Nevada         110567
28         New Hampshire           9351
29            New Jersey           8722
30            New Mexico         121593
31              New York          54475
32        North Carolina          53821
33          North Dakota          70704
34                  Ohio          44828
35              Oklahoma          69903
36                Oregon          98386
37          Pennsylvania          46058
38          Rhode Island           1545
39        South Carolina          32007
40          South Dakota          77121
41             Tennessee          42146
42                 Texas         268601
43                  Utah          84904
44               Vermont           9615
45              Virginia          42769
46            Washington          71303
47         West Virginia          24231
48             Wisconsin          65503
49               Wyoming          97818
50  District of Columbia             68
51           Puerto Rico           3515
                   state abbreviation
0                Alabama           AL
1                 Alaska           AK
2                Arizona           AZ
3               Arkansas           AR
4             California           CA
5               Colorado           CO
6            Connecticut           CT
7               Delaware           DE
8   District of Columbia           DC
9                Florida           FL
10               Georgia           GA
11                Hawaii           HI
12                 Idaho           ID
13              Illinois           IL
14               Indiana           IN
15                  Iowa           IA
16                Kansas           KS
17              Kentucky           KY
18             Louisiana           LA
19                 Maine           ME
20               Montana           MT
21              Nebraska           NE
22                Nevada           NV
23         New Hampshire           NH
24            New Jersey           NJ
25            New Mexico           NM
26              New York           NY
27        North Carolina           NC
28          North Dakota           ND
29                  Ohio           OH
30              Oklahoma           OK
31                Oregon           OR
32              Maryland           MD
33         Massachusetts           MA
34              Michigan           MI
35             Minnesota           MN
36           Mississippi           MS
37              Missouri           MO
38          Pennsylvania           PA
39          Rhode Island           RI
40        South Carolina           SC
41          South Dakota           SD
42             Tennessee           TN
43                 Texas           TX
44                  Utah           UT
45               Vermont           VT
46              Virginia           VA
47            Washington           WA
48         West Virginia           WV
49             Wisconsin           WI
50               Wyoming           WY
51           Puerto Rico           PR

---
## 2. 데이타 연결
        
    1- 인구 데이타(pop)와 주이름 약어 데이타(abbrevs)를 연결
            ( 각 주의 전체 이름과 인구를 볼 수 있도록 )
    2- 각 주의 인구 데이타(pop)와 면적 데이타(areas)를 연결
            ( 각 주의 면적당 인구를 계산하여 인구 밀도를 구하기 )

In [47]:
result1= pop.merge(abbrevs,left_on = 'state/region',right_on = 'abbreviation',how ='outer')
result1

result2= result1.merge(areas,left_on = 'state',right_on = 'state', how ='outer')
result2

#2010년만 sorting
result_2010 = result2[(result2['year'] == 2010)]
result_2010

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
2,AL,under18,2010,1130966.0,Alabama,AL,52423.0
3,AL,total,2010,4785570.0,Alabama,AL,52423.0
90,AK,under18,2010,187902.0,Alaska,AK,656425.0
91,AK,total,2010,713868.0,Alaska,AK,656425.0
100,AZ,under18,2010,1628563.0,Arizona,AZ,114006.0
101,AZ,total,2010,6408790.0,Arizona,AZ,114006.0
188,AR,under18,2010,711947.0,Arkansas,AR,53182.0
189,AR,total,2010,2922280.0,Arkansas,AR,53182.0
196,CA,under18,2010,9284094.0,California,CA,163707.0
197,CA,total,2010,37333601.0,California,CA,163707.0
282,CO,under18,2010,1226619.0,Colorado,CO,104100.0
283,CO,total,2010,5048196.0,Colorado,CO,104100.0
292,CT,under18,2010,814187.0,Connecticut,CT,5544.0
293,CT,total,2010,3579210.0,Connecticut,CT,5544.0
378,DE,under18,2010,205478.0,Delaware,DE,1954.0
379,DE,total,2010,899711.0,Delaware,DE,1954.0
388,DC,under18,2010,101309.0,District of Columbia,DC,68.0
389,DC,total,2010,605125.0,District of Columbia,DC,68.0
474,FL,under18,2010,3999532.0,Florida,FL,65758.0
475,FL,total,2010,18846054.0,Florida,FL,65758.0
484,GA,under18,2010,2490884.0,Georgia,GA,59441.0
485,GA,total,2010,9713248.0,Georgia,GA,59441.0
570,HI,total,2010,1363731.0,Hawaii,HI,10932.0
571,HI,under18,2010,303812.0,Hawaii,HI,10932.0
580,ID,under18,2010,428961.0,Idaho,ID,83574.0
581,ID,total,2010,1570718.0,Idaho,ID,83574.0
666,IL,total,2010,12839695.0,Illinois,IL,57918.0
667,IL,under18,2010,3122092.0,Illinois,IL,57918.0
676,IN,under18,2010,1605883.0,Indiana,IN,36420.0
677,IN,total,2010,6489965.0,Indiana,IN,36420.0
...,...,...,...,...,...,...,...
1828,PA,under18,2010,2785316.0,Pennsylvania,PA,46058.0
1829,PA,total,2010,12710472.0,Pennsylvania,PA,46058.0
1914,RI,total,2010,1052669.0,Rhode Island,RI,1545.0
1915,RI,under18,2010,223088.0,Rhode Island,RI,1545.0
1924,SC,under18,2010,1079978.0,South Carolina,SC,32007.0
1925,SC,total,2010,4636361.0,South Carolina,SC,32007.0
2010,SD,total,2010,816211.0,South Dakota,SD,77121.0
2011,SD,under18,2010,203145.0,South Dakota,SD,77121.0
2020,TN,under18,2010,1495090.0,Tennessee,TN,42146.0
2021,TN,total,2010,6356683.0,Tennessee,TN,42146.0
2106,TX,total,2010,25245178.0,Texas,TX,268601.0
2107,TX,under18,2010,6879014.0,Texas,TX,268601.0
2116,UT,under18,2010,873019.0,Utah,UT,84904.0
2117,UT,total,2010,2774424.0,Utah,UT,84904.0
2202,VT,total,2010,625793.0,Vermont,VT,9615.0
2203,VT,under18,2010,128601.0,Vermont,VT,9615.0
2212,VA,under18,2010,1855025.0,Virginia,VA,42769.0
2213,VA,total,2010,8024417.0,Virginia,VA,42769.0
2298,WA,total,2010,6742256.0,Washington,WA,71303.0
2299,WA,under18,2010,1581436.0,Washington,WA,71303.0
2308,WV,under18,2010,387224.0,West Virginia,WV,24231.0
2309,WV,total,2010,1854146.0,West Virginia,WV,24231.0
2394,WI,total,2010,5689060.0,Wisconsin,WI,65503.0
2395,WI,under18,2010,1336094.0,Wisconsin,WI,65503.0
2404,WY,under18,2010,135351.0,Wyoming,WY,97818.0
2405,WY,total,2010,564222.0,Wyoming,WY,97818.0
2490,PR,total,2010,3721208.0,Puerto Rico,PR,3515.0
2491,PR,under18,2010,896945.0,Puerto Rico,PR,3515.0
2538,USA,under18,2010,74119556.0,NaN,NaN,NaN
2539,USA,total,2010,309326295.0,NaN,NaN,NaN

---
##  3. 데이타 정제 -    누락값 처리

        (1) 삭제한다
        (2) 대체한다
    
    실제로 2000년 이전의 PR(푸에르토리토)의 인구 데이타가 없는 것이다.
    여기서는 2010년 데이타를 구할 것이기에 삭제해도 되지만 대체하는 방식을 연습한다
    또한 전체 미국을 뜻하는 USA에 state와 abbreviation이 없다.

In [54]:
# (1) null 값 확인

# (2) 우선 state 컬럼의 null 처리

## 4. 각 주의 인구를 연결한 데이타셋에 주의 면적 데이타 셋을 연결하기 

(merge이용)


#### 1- pop과 abbreviation의 연결한 데이타셋과 areas(면적) 데이타셋을 연결

#### 2-널 값 여부 확인

#### 3- 널값 확인

#### 4- 널값 처리 : 데이타 삭제하기
    미국 전역에 대한 데이타는 인구 밀도와 관련이 없기에 삭제
    
#### 5- 면적이 null 값이 있는지 없는지 확인

In [57]:
# 각 주의 인구를 연결한 데이타셋에 주의 면적 데이타 셋을 연결하기
# 1- pop과 abbreviation의 연결한 데이타셋과 areas(면적) 데이타셋을 연결
# 2-널 값 여부 확인
result_2010.isnull()
# 3- 널값 확인 : 면적값이 널인 주를 찾으면
result_2010[result_2010['area (sq. mi)'].isnull()]

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
2538,USA,under18,2010,74119556.0,NaN,NaN,NaN
2539,USA,total,2010,309326295.0,NaN,NaN,NaN

In [59]:
# 4- 널값 처리 : 데이타 삭제하기
# 미국 전역에 대한 데이타는 인구 밀도와 관련이 없기에 삭제
result_2010 = result_2010.dropna()
result_2010

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
2,AL,under18,2010,1130966.0,Alabama,AL,52423.0
3,AL,total,2010,4785570.0,Alabama,AL,52423.0
90,AK,under18,2010,187902.0,Alaska,AK,656425.0
91,AK,total,2010,713868.0,Alaska,AK,656425.0
100,AZ,under18,2010,1628563.0,Arizona,AZ,114006.0
101,AZ,total,2010,6408790.0,Arizona,AZ,114006.0
188,AR,under18,2010,711947.0,Arkansas,AR,53182.0
189,AR,total,2010,2922280.0,Arkansas,AR,53182.0
196,CA,under18,2010,9284094.0,California,CA,163707.0
197,CA,total,2010,37333601.0,California,CA,163707.0
282,CO,under18,2010,1226619.0,Colorado,CO,104100.0
283,CO,total,2010,5048196.0,Colorado,CO,104100.0
292,CT,under18,2010,814187.0,Connecticut,CT,5544.0
293,CT,total,2010,3579210.0,Connecticut,CT,5544.0
378,DE,under18,2010,205478.0,Delaware,DE,1954.0
379,DE,total,2010,899711.0,Delaware,DE,1954.0
388,DC,under18,2010,101309.0,District of Columbia,DC,68.0
389,DC,total,2010,605125.0,District of Columbia,DC,68.0
474,FL,under18,2010,3999532.0,Florida,FL,65758.0
475,FL,total,2010,18846054.0,Florida,FL,65758.0
484,GA,under18,2010,2490884.0,Georgia,GA,59441.0
485,GA,total,2010,9713248.0,Georgia,GA,59441.0
570,HI,total,2010,1363731.0,Hawaii,HI,10932.0
571,HI,under18,2010,303812.0,Hawaii,HI,10932.0
580,ID,under18,2010,428961.0,Idaho,ID,83574.0
581,ID,total,2010,1570718.0,Idaho,ID,83574.0
666,IL,total,2010,12839695.0,Illinois,IL,57918.0
667,IL,under18,2010,3122092.0,Illinois,IL,57918.0
676,IN,under18,2010,1605883.0,Indiana,IN,36420.0
677,IN,total,2010,6489965.0,Indiana,IN,36420.0
...,...,...,...,...,...,...,...
1818,OR,total,2010,3837208.0,Oregon,OR,98386.0
1819,OR,under18,2010,865129.0,Oregon,OR,98386.0
1828,PA,under18,2010,2785316.0,Pennsylvania,PA,46058.0
1829,PA,total,2010,12710472.0,Pennsylvania,PA,46058.0
1914,RI,total,2010,1052669.0,Rhode Island,RI,1545.0
1915,RI,under18,2010,223088.0,Rhode Island,RI,1545.0
1924,SC,under18,2010,1079978.0,South Carolina,SC,32007.0
1925,SC,total,2010,4636361.0,South Carolina,SC,32007.0
2010,SD,total,2010,816211.0,South Dakota,SD,77121.0
2011,SD,under18,2010,203145.0,South Dakota,SD,77121.0
2020,TN,under18,2010,1495090.0,Tennessee,TN,42146.0
2021,TN,total,2010,6356683.0,Tennessee,TN,42146.0
2106,TX,total,2010,25245178.0,Texas,TX,268601.0
2107,TX,under18,2010,6879014.0,Texas,TX,268601.0
2116,UT,under18,2010,873019.0,Utah,UT,84904.0
2117,UT,total,2010,2774424.0,Utah,UT,84904.0
2202,VT,total,2010,625793.0,Vermont,VT,9615.0
2203,VT,under18,2010,128601.0,Vermont,VT,9615.0
2212,VA,under18,2010,1855025.0,Virginia,VA,42769.0
2213,VA,total,2010,8024417.0,Virginia,VA,42769.0
2298,WA,total,2010,6742256.0,Washington,WA,71303.0
2299,WA,under18,2010,1581436.0,Washington,WA,71303.0
2308,WV,under18,2010,387224.0,West Virginia,WV,24231.0
2309,WV,total,2010,1854146.0,West Virginia,WV,24231.0
2394,WI,total,2010,5689060.0,Wisconsin,WI,65503.0
2395,WI,under18,2010,1336094.0,Wisconsin,WI,65503.0
2404,WY,under18,2010,135351.0,Wyoming,WY,97818.0
2405,WY,total,2010,564222.0,Wyoming,WY,97818.0
2490,PR,total,2010,3721208.0,Puerto Rico,PR,3515.0
2491,PR,under18,2010,896945.0,Puerto Rico,PR,3515.0

In [60]:
# 5- [결과확인] 면적이 null 값이 있는지 없는지 확인

result_2010[result_2010['area (sq. mi)'].isnull()]

Empty DataFrame
Columns: [state/region, ages, year, population, state, abbreviation, area (sq. mi)]
Index: []

## 2010년 인구밀도 계산하고 표현
        
        
    인구밀도 = 인구 / 면적
        
    필요한 데이타는 2010년 전체 인구에 대한 데이타집합이다.

In [67]:
'''

# 필요한 데이타집합 추출
data = finalmerged[finalmerged['year']==2010]
data = data[finalmerged['ages']=='total']
# print(data)

# 주(state)를 기준으로 데이타 인덱스를 정하고 인구밀도 계산
data.set_index('state', inplace=True)
# print(data)


density = data['population']/data['area (sq. mi)']
density

density.sort_values(ascending=False, inplace=True)
print(density)  
'''


def density(population,area) :
    return population/area

result_2010['density']=result_2010.apply(lambda x :density(x['population'],x['area (sq. mi)']),axis = 1)
result_2010.sort_values('density',ascending=0)

,state/region,ages,year,population,state,abbreviation,area (sq. mi),density
389,DC,total,2010,605125.0,District of Columbia,DC,68.0,8898.897059
388,DC,under18,2010,101309.0,District of Columbia,DC,68.0,1489.838235
2490,PR,total,2010,3721208.0,Puerto Rico,PR,3515.0,1058.665149
1445,NJ,total,2010,8802707.0,New Jersey,NJ,8722.0,1009.253268
1914,RI,total,2010,1052669.0,Rhode Island,RI,1545.0,681.339159
293,CT,total,2010,3579210.0,Connecticut,CT,5544.0,645.600649
1050,MA,total,2010,6563263.0,Massachusetts,MA,10555.0,621.815538
965,MD,total,2010,5787193.0,Maryland,MD,12407.0,466.445797
379,DE,total,2010,899711.0,Delaware,DE,1954.0,460.445752
1541,NY,total,2010,19398228.0,New York,NY,54475.0,356.094135
475,FL,total,2010,18846054.0,Florida,FL,65758.0,286.597129
1829,PA,total,2010,12710472.0,Pennsylvania,PA,46058.0,275.966651
1722,OH,total,2010,11545435.0,Ohio,OH,44828.0,257.549634
2491,PR,under18,2010,896945.0,Puerto Rico,PR,3515.0,255.176387
1444,NJ,under18,2010,2062013.0,New Jersey,NJ,8722.0,236.415157
197,CA,total,2010,37333601.0,California,CA,163707.0,228.051342
666,IL,total,2010,12839695.0,Illinois,IL,57918.0,221.687472
2213,VA,total,2010,8024417.0,Virginia,VA,42769.0,187.622273
677,IN,total,2010,6489965.0,Indiana,IN,36420.0,178.197831
1626,NC,total,2010,9559533.0,North Carolina,NC,53821.0,177.617157
485,GA,total,2010,9713248.0,Georgia,GA,59441.0,163.409902
2021,TN,total,2010,6356683.0,Tennessee,TN,42146.0,150.825298
292,CT,under18,2010,814187.0,Connecticut,CT,5544.0,146.859127
1925,SC,total,2010,4636361.0,South Carolina,SC,32007.0,144.854594
1915,RI,under18,2010,223088.0,Rhode Island,RI,1545.0,144.393528
1434,NH,total,2010,1316614.0,New Hampshire,NH,9351.0,140.799273
1051,MA,under18,2010,1415962.0,Massachusetts,MA,10555.0,134.150829
570,HI,total,2010,1363731.0,Hawaii,HI,10932.0,124.746707
964,MD,under18,2010,1351983.0,Maryland,MD,12407.0,108.969372
858,KY,total,2010,4347698.0,Kentucky,KY,40411.0,107.586994
...,...,...,...,...,...,...,...,...
2395,WI,under18,2010,1336094.0,Wisconsin,WI,65503.0,20.397447
581,ID,total,2010,1570718.0,Idaho,ID,83574.0,18.794338
1530,NM,total,2010,2064982.0,New Mexico,NM,121593.0,16.982737
2308,WV,under18,2010,387224.0,West Virginia,WV,24231.0,15.980521
1156,MS,under18,2010,754111.0,Mississippi,MS,48434.0,15.569868
1147,MN,under18,2010,1282693.0,Minnesota,MN,86943.0,14.753264
100,AZ,under18,2010,1628563.0,Arizona,AZ,114006.0,14.284889
188,AR,under18,2010,711947.0,Arkansas,AR,53182.0,13.386992
2203,VT,under18,2010,128601.0,Vermont,VT,9615.0,13.375039
1732,OK,under18,2010,931483.0,Oklahoma,OK,69903.0,13.325365
763,IA,under18,2010,727717.0,Iowa,IA,56276.0,12.931214
282,CO,under18,2010,1226619.0,Colorado,CO,104100.0,11.783084
2010,SD,total,2010,816211.0,South Dakota,SD,77121.0,10.583512
2116,UT,under18,2010,873019.0,Utah,UT,84904.0,10.282425
1637,ND,total,2010,674344.0,North Dakota,ND,70704.0,9.537565
772,KS,under18,2010,727729.0,Kansas,KS,82282.0,8.844328
1819,OR,under18,2010,865129.0,Oregon,OR,98386.0,8.793212
955,ME,under18,2010,273061.0,Maine,ME,35387.0,7.716421
1253,MT,total,2010,990527.0,Montana,MT,147046.0,6.736171
1348,NV,under18,2010,663180.0,Nevada,NV,110567.0,5.997992
1339,NE,under18,2010,459621.0,Nebraska,NE,77358.0,5.941480
2405,WY,total,2010,564222.0,Wyoming,WY,97818.0,5.768079
580,ID,under18,2010,428961.0,Idaho,ID,83574.0,5.132709
1531,NM,under18,2010,518763.0,New Mexico,NM,121593.0,4.266389
2011,SD,under18,2010,203145.0,South Dakota,SD,77121.0,2.634107
1636,ND,under18,2010,150179.0,North Dakota,ND,70704.0,2.124052
1252,MT,under18,2010,223292.0,Montana,MT,147046.0,1.518518
2404,WY,under18,2010,135351.0,Wyoming,WY,97818.0,1.383702
91,AK,total,2010,713868.0,Alaska,AK,656425.0,1.087509
90,AK,under18,2010,187902.0,Alaska,AK,656425.0,0.286251

### [결과] 

        state
        District of Columbia    8898.897059
        New Jersey              1009.253268
        Rhode Island             681.339159
        Connecticut              645.600649
        Massachusetts            621.815538
        Maryland                 466.445797
        Delaware                 460.445752
        New York                 356.094135
        Florida                  286.597129
        Pennsylvania             275.966651
        Ohio                     257.549634
        California               228.051342
        Illinois                 221.687472
        Virginia                 187.622273
        Indiana                  178.197831
        North Carolina           177.617157
        Georgia                  163.409902
        Tennessee                150.825298
        South Carolina           144.854594
        New Hampshire            140.799273
        Hawaii                   124.746707
        Kentucky                 107.586994
        Michigan                 102.015794
        Washington                94.557817
        Texas                     93.987655
        Alabama                   91.287603
        Louisiana                 87.676099
        Wisconsin                 86.851900
        Missouri                  86.015622
        West Virginia             76.519582
        Vermont                   65.085075
        Mississippi               61.321530
        Minnesota                 61.078373
        Arizona                   56.214497
        Arkansas                  54.948667
        Iowa                      54.202751
        Oklahoma                  53.778278
        Colorado                  48.493718
        Oregon                    39.001565
        Maine                     37.509990
        Kansas                    34.745266
        Utah                      32.677188
        Nevada                    24.448796
        Nebraska                  23.654153
        Idaho                     18.794338
        New Mexico                16.982737
        South Dakota              10.583512
        North Dakota               9.537565
        Montana                    6.736171
        Wyoming                    5.768079
        Alaska                     1.087509


---


  [분석결과]
  
  인구 밀도가 가장 높은 주는 District of Columbia(DC) 워싱톤DC 이고
  그 다음은 Puerto Rico 이다.
  
  인구 밀도가 가장 작은 Alaska는 1제곱마일당 평균 주민수가 1만명정도이다.
  
  [시각화작업]